### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by rwatts3** [sigmeus/meteor-desktop-app#4]
Can I buikd desktop based apps with this package ?

**Comment by fix** [comment]
Yes, using a client-server architecture on the same machine. See Kitematic or atom.io for a good example.

**Comment by hitchcott** [comment]
Thanks for the script @fix. Do you know of any examples with Meteor?

**Comment by fix** [comment]
Yes, recent interesting app is https://sandstorm.io/ could be interesting port on desktop app.

**Comment by IstoraMandiri** [comment]
Thanks @fix. Sandstorm would indeed be cool, although there are a lot of things going on other than Meteor.

Do you happen to know of any actual code examples of a Meteor client + server desktop app -- even just `hello world`?

**Comment by fix** [comment]
no
